version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbnest:/var/lib/mysql:rw

volumes:
  dbnest: 
